---
# tasks file for kernel


# Copy the kernel settings to remote
  - name: Copy the kernel settings to remote
    copy:
      src: "{{ item }}"
      dest: /etc/sysctl.conf
      owner: root
      group: root
      mode: 0600
    loop:
      - kernel
