---
# tasks file for common

#-----------------------------------------------------------------------
# Title         : Copy files to the correct locations on remote client
#
# Script        : main.yml
# Description   : Copy files to the correct locations on remote client
# Dependencies  : ansible, python, ssh
# Usage         : ansible-playbook <file> -bk
# Author        : Fai Tao
# Version       : 0.1
# Date          : 03 Feb 2020
#
# Change history (most recent first)
#
# Date          Who             Comments
# ----          ---             --------
# 03/02/20      FT              Initial draft
#-----------------------------------------------------------------------


# Copy files to correct locations on remote client -----------------------------------------------
  - name: Copy files to the correct locations on remote client
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: "{{ item.mode }}"
    loop:
      - { src: 'sshd_config', dest: '/etc/ssh/sshd_config', mode: '0600'}
