---
# tasks file for loginDefs

# Copy the base login.defs to remote
  - name: Copy the base login.defs to remote
    copy:
      src: "{{ item }}"
      dest: /etc/login.defs
      owner: root
      group: root
      mode: 0640
    loop:
      - loginDefs8
    when: ansible_distribution_major_version == '8'


# Copy the base login.defs to remote
  - name: Copy the base login.defs to remote
    copy:
      src: "{{ item }}"
      dest: /etc/login.defs
      owner: root
      group: root
      mode: 0640
    loop:
      - loginDefs7
    when: ansible_distribution_major_version == '7'
