---

#-----------------------------------------------------------------------
# Title         : Set the /root/.message file for the console
#
# Script        : main.yml
# Description   : Set the /root/.message file for the console
# Dependencies  : ansible, python, ssh, set_message.sh, scriptran.sh
# Usage         : ansible-playbook <file> -bk
# Author        : Fai Tao
# Version       : 0.1
# Date          : 04 Mar 2020
#
# Change history (most recent first)
#
# Date          Who             Comments
# ----          ---             --------
# 04/03/20      FT              Initial draft
#-----------------------------------------------------------------------

# To make shell scripts idempotent we create a file after the script is run.
# The presence of the control file determines if the script is run again.

  - name: Copy over the console.sh script to remote and run on remote boxes - RUN ONCE ONLY
    script: "{{ item }}"
    with_items:
      - set_message.sh
    args:
      chdir: /home/ftao
      creates: s1.ran

